app:
  name: "musannif"
  sqlite_directory: "/var/db/musannif/"
  log_directory: "/var/log/musannif/"
  note_directory: "/var/opt/musannif/"
  environment: "debug"
server:
  host: "localhost"
  port: 8242
secrets:
  JWT_ACCESS_SECRET: ""
  JWT_REFRESH_SECRET: ""
